#!/bin/sh

mkdir -p /tmp/photocan/backup
mkdir -p /tmp/photocan/upload

name=`basename $UM_MOUNTPOINT`
touch /tmp/photocan/backup/$name
logger Checking $name for photos to be backued up
/usr/local/bin/backup-photos $UM_MOUNTPOINT
RETVAL="$?"
if [ "$RETVAL" = 1 ]; then
	# Need to upload photos later
	mv /tmp/photocan/backup/$name /tmp/photocan/upload/$name
else
	rm /tmp/photocan/backup/$name
	umount $UM_MOUNTPOINT
fi
