#!/bin/sh

logger -t photocan $UM_MOUNTPOINT has been unmounted

mkdir -p /tmp/photocan/backup
mkdir -p /tmp/photocan/upload
mkdir -p /tmp/photocan/uploading

if [ -z "$(ls -A /tmp/photocan/backup/)"]; then
	list=`ls -A /tmp/photocan/upload/`
	if [ -n "$list" ]; then
		for name in $list; do
			mountpoint=`cat /tmp/photocan/upload/$name`
			path=/tmp/photocan/upload/$name
			lockpath=/tmp/photocan/uploading/$name
			if { mv $path $lockpath ; }; then
			# Avoid race condition
				logger -t photocan Uploading photos to $mountpoint
				/usr/local/bin/upload-photos $mountpoint
				umount $mountpoint
				rm $lockpath
			fi
		done
	fi
fi

if [ -z "$(ls -A /tmp/photocan/backup/)"] && \
	 [ -z "$(ls -A /tmp/photocan/upload/)"] && \
	 [ -z "$(ls -A /tmp/photocan/uploading/)"]; then
	switch=/tmp/photocan/poweroff.$$
	touch $switch
	logger "Power off in 15 seconds. sudo rm -f $switch to avoid power off"
	sleep 15
	sync; sync
	if [ -e $switch ]; then
		logger Turnning power off
		sync; sync; sync; poweroff
	else
		logger Stopped turnning power off
	fi
fi
