#!/bin/sh

mkdir -p /tmp/photocan/backup
mkdir -p /tmp/photocan/upload
mkdir -p /tmp/photocan/uploading

if [ -z "$(ls -A /tmp/photocan/backup/)"]; then
	list=`ls -A /tmp/photocan/upload/`
	if [ -n "$list" ]; then
		for name in $list; do
			mountpoint=`cat /tmp/photocan/upload/$name`
			path=/tmp/photocan/upload/$name
			lockpath=/tmp/photocan/uploading/$name
			if { mv $path $lockpath ; }; then
			# Avoid race condition
				logger Uploading photos to $mountpoint
				/usr/local/bin/upload-photos $mountpoint
				umount $mountpoint
				rm $lockpath
			fi
		done
	fi
fi

if [ -z "$(ls -A /tmp/photocan/backup/)"] && \
	 [ -z "$(ls -A /tmp/photocan/upload/)"] && \
	 [ -z "$(ls -A /tmp/photocan/uploading/)"]; then
	logger Power off in 15 seconds
	touch /tmp/photocan/poweroff
	sleep 15
	if [ -e /tmp/photocan/poweroff ]; then
		logger Turnning power off
		sync; sync; sync; poweroff
	fi
fi
